### ISSUE TITLE
No octal numbers in json, jessie, ses, or es-strict

### ISSUE THREAD

**Issue by erights** [michaelfig/jessica#2]
https://github.com/michaelfig/jessica/blob/ebb045a2afbf5bfec1f4f6b3da7aee04b4d45c65/lib/boot-peg.mjs#L194
says
> // FIXME: Handle octal integers.

To be clear, the handling should be to report a syntax error. See json grammar

**Comment by michaelfig** [comment]
Actually, the octal support is only for the peg tag, which needs it to
bootstrap the utf8 support I'm adding to the JSON grammar.

json and its derivatives will not support octal (just as they don't support
any of the other quasi-peg.mjs productions).

**Comment by erights** [comment]
Aha! Makes sense.

**Comment by michaelfig** [comment]
Just to be more consistent, quasi-peg.mjs has dropped support for octal, and now only supports `\xFF`-style character codes.

**Comment by erights** [comment]
See http://json.org . Please support only \uFFFF .

**Comment by michaelfig** [comment]
As described before, this is only a change to the grammar for peg grammars.  quasi-json.mjs continues to accept only `\uFFFF`.
